pref("extensions.desktop.thumbnail.width", 286);
pref("extensions.desktop.thumbnail.height", 222);
pref("extensions.desktop.gridInterval", 32);
pref("extensions.desktop.backgroundStyle", 1);
pref("extensions.desktop.focus", "");
pref("extensions.desktop.lock", false);
pref("extensions.desktop.showDecorations", true);
pref("extensions.desktop.overrideNewTab", true);
pref("extensions.desktop.overrideHomePage", false);
